app = "coastsquash"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/usr/share/nginx/html/"
  url_prefix = "/"
