# fly.toml app configuration file generated for coastsquash on 2023-10-30T14:46:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coastsquash"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/usr/share/nginx/html/"
  url_prefix = "/"
